version: "3.1"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  sales-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  # sales-db:
  #   image: tutum/mongodb
  #   container_name: sales-db
  #   restart: always
  #   environment:
  #     - MONGODB_USER=admin
  #     - MONGODB_DATABASE=sales-db
  #     - MONGODB_PASS=123456
  #   ports:
  #     - 27017:27017
  #     - 28017:28017

  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
